<a href="https://colab.research.google.com/github/Laluprasad1/AIML-2025/blob/main/Lab01_AIML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Lab01- Implement basic data structures of Numpy, Pandas, Matplotlib and Access Data from sources**

# **Part 01: Lab Task is implement the following data structures using Numpy and Pandas.**

In [13]:
import numpy as np
l1=[1,2,3,4,5]
arr1 = np.array(l1)
arr1

array([1, 2, 3, 4, 5])

In [8]:
#type of list
type(l1)

list

In [9]:
#type of array
type(arr1)

numpy.ndarray

Perform Mathematical Operations on these datasets - Multiplication, Division, Poweroff

In [15]:
l2=[5,4,3,2,1]
arr2=np.array(l2)
arr2

array([5, 4, 3, 2, 1])

In [18]:
print("Addition of arr1 and arr2: ",arr1+arr2)
print("Subtraction of arr1 and arr2: ",arr1-arr2)
print("Multiplication of arr2 and arr1: ",arr1*arr2)
print("Division of arr2 and arr1: ",arr2/arr1)
print("arr2 raised to the power of arr1: ",arr2**arr1)
print(f" {arr2} raised to the power of {arr1}: {arr2**arr1}")

Addition of arr1 and arr2:  [6 6 6 6 6]
Subtraction of arr1 and arr2:  [-4 -2  0  2  4]
Multiplication of arr2 and arr1:  [5 8 9 8 5]
Division of arr2 and arr1:  [5.  2.  1.  0.5 0.2]
arr2 raised to the power of arr1:  [ 5 16 27 16  1]
 [5 4 3 2 1] raised to the power of [1 2 3 4 5]: [ 5 16 27 16  1]


In [22]:
# sine function
print("Sine of array1: ",np.sin(arr1))
print("Sine of array2: ",np.sin(arr2))
#cos function
print("Cosine of array1: ",np.cos(arr1))
print("Cosine of array2: ",np.sin(arr2))
# logarithm
print("Natural logarithm: ",np.log(arr1))
print("Base-10 logarithm: ",np.log10(arr1))
print("Base-2 logarithm: ",np.log2(arr1))
# Exponential
print("Exponential: ",np.exp(arr1))

Sine of array1:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Sine of array2:  [-0.95892427 -0.7568025   0.14112001  0.90929743  0.84147098]
Cosine of array1:  [ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]
Cosine of array2:  [-0.95892427 -0.7568025   0.14112001  0.90929743  0.84147098]
Natural logarithm:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Base-10 logarithm:  [0.         0.30103    0.47712125 0.60205999 0.69897   ]
Base-2 logarithm:  [0.         1.         1.5849625  2.         2.32192809]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
